language: cpp

services:
  - docker

branches:
  only:
    - master
    - dev

install:
- docker pull devkitpro/devkita64

script:
- docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/Chocolate-Doom-Launcher devkitpro/devkita64 /bin/bash -ex /Chocolate-Doom-Launcher/.travis/.build.sh
