name: CI

on:
  push:
    branches:
    - master
    - dev

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Update and Install Build Dependencies
      run: apt-get update && apt-get install -y apt-utils && apt-get install -y --no-install-recommends sudo ca-certificates pkg-config curl wget bzip2 xz-utils make git bsdtar doxygen gnupg && apt-get clean
    - name: Install devkitPro
      run: wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb && dpkg -i devkitpro-pacman.deb && rm devkitpro-pacman.deb && dkp-pacman -Scc --noconfirm && source /etc/profile.d/devkit-env.sh
    - name: Install Switch Toolchain
      run: dkp-pacman -Syyu --noconfirm switch-dev && dkp-pacman -S --needed --noconfirm switch-curl switch-mbedtls switch-libjpeg-turbo switch-libpng switch-libwebp switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-sdl2_ttf switch-zlib && dkp-pacman -Scc --noconfirm
    - uses: actions/checkout@v2
    - name: Build
      run: make
